### ISSUE TITLE
Can't add a datasource

### ISSUE THREAD

**Issue by Atem18** [etichy/grafana-swis-datasource#1]
Hi @etichy ,

I cannot add a datasource, I have the following error : 
```
Invalid SWIS uri at character 12: Incomplete uri. Parser did not finish in End state, but instead was left in Scheme state
 Parameter name: uri
```

I think it's because for me : https://localhost:17778/SolarWinds/InformationService/v3/Json/openapi.json does not work.

I think you should test with : https://localhost:17778/SolarWinds/InformationService/v3/Json/Query?query=SELECT+Uri+FROM+Orion.Pollers+ORDER+BY+PollerID+WITH+ROWS+1+TO+3+WITH+TOTALROWS

Src: https://github.com/solarwinds/OrionSDK/wiki/REST

**Comment by etichy** [comment]
it should work without issue. Can you pass this URI into your browser? You should get all REST API commands of SWIS service. 

I know it will be silly question, but are you running grafana server on orion server?

**Comment by Atem18** [comment]
@etichy I know I tried it already but I get no answer.

And no of course, but I already tried to make SWIS requests via curl and they work from grafana server.

**Comment by etichy** [comment]
Hmmm which SWIS version are you running? This is probably something new. I will add version check, thanks.

**Comment by Atem18** [comment]
@etichy I am using 2018.2 and they released Swagger/OpenAPI in 2018.4 : https://thwack.solarwinds.com/thread/123515

**Comment by junaid360** [comment]
Im having the same issue. 

Message | "Invalid SWIS uri at character 0: Incomplete uri. Parser did not finish in End state, but instead was left in Scheme state\r\nParameter name: uri"
-- | --

**Comment by etichy** [comment]
oki, let me fix it asap.

**Comment by etichy** [comment]
Fixed by changing TestDataSource URI -.... /Query?query=SELECT Description FROM System.NullEntity

**Comment by junaid360** [comment]
can you give full output to add to test? thanks

**Comment by junaid360** [comment]
Works. thank you

**Comment by junaid360** [comment]
After adding new files, the plugin stop working.

![image](https://user-images.githubusercontent.com/52662643/61226325-e3926d00-a72a-11e9-9249-f10c538a279b.png)
