### ISSUE TITLE
Addind String to Output

### ISSUE THREAD

**Issue by mjs2012** [etichy/grafana-swis-datasource#12]
Hey Edward,

Thanks for creating this plugin for Grafana, it is very cool and helps a lot.

I have created teh following query:
```
SELECT downsample(d.DateTime) as time,
  d.FullName,
  AVG(d.InPercentUtil) as InPercentUtil
FROM (
SELECT 
 i.Fullname,
 i.Traffic.DateTime,
 i.Traffic.InPercentUtil 
 as InPercentUtil
FROM Orion.NPM.Interfaces as i
WHERE InterfaceID IN ($Interface)
) as d
WHERE d.DateTime BETWEEN $from AND $to
GROUP BY downsample(d.DateTime), d.Fullname
ORDER BY time DESC
```

I get now the following output for example:
![grafik](https://user-images.githubusercontent.com/3264365/95787184-492c2b00-0cd9-11eb-9518-030686e207da.png)

Is it possible to add an string to the output, for example "SW-CENTRAL - 9 out" instead of only "SW-CENTRAL - 9".
If that can be done, so can I combine "in" and "out" traffic in one graph.

Thanks a lot and best Regards,
Matthias

**Comment by etichy** [comment]
SWQL supports string operators + other [functions](https://github.com/solarwinds/OrionSDK/wiki/SWQL-Functions), so for your case you can write something like this
```
d.FullName + ' out' as FullName
```
