### ISSUE TITLE
Plugin unsigned with Grafana v7.3.1 (6668161a88)

### ISSUE THREAD

**Issue by svestenik** [etichy/grafana-swis-datasource#13]
Hello,

I have noticed that after upgrade to v7.3.1 swis datasource plugin shows as unsigned.

Can you add signature to the plugin ?

**Comment by etichy** [comment]
Yeah, since grafana 7.1 unsigned plugins are not loaded by default.

https://github.com/grafana/grafana/issues/24027

**Comment by natarajanmurukan** [comment]
Thanks a lot @etichy . I was struggling for a week to resolve this issue. Now I have downgraded to 7.0.6 version which serve my purpose.
