### ISSUE TITLE
An Issue after a Grafana upgrade

### ISSUE THREAD

**Issue by awer1967** [etichy/grafana-swis-datasource#16]
Hi !
We have been using your plugin for over 1.5 year , it worked fine. No issues

We have upgraded our Grafana to v.8.1.1

The plugin is out of order now.

When I select  its page in a Datasources menu and   pushed a button "Save&Test" in its screen there ,it raises an error

**Cannot read property 'status' of undefined**

All settings there are the same as in your documentation

I have updated the plugin to the latest version. No luck at all.
What could be wrong ?

Add.1 We have realized that in case you aren't logged in Grafana as user , you are able to see all data on Grafana's boards based on your Datasource. But if we logged in it would stop work immediately.

**Comment by etichy** [comment]
Hi, I tried grafana 8.4.6 and it works as usual. The only problem is that by default grafana doesn't load not signed plugins. So you have to allow it in conf/defaults.ini

allow_loading_unsigned_plugins = solarwinds-swis-datasource
