### ISSUE TITLE
Plugin grafana-swis-datasource-develop not compactible on Grafana 9. Same plugin was working fine in version 6. 

### ISSUE THREAD

**Issue by Karthick31** [etichy/grafana-swis-datasource#17]
Plugin grafana-swis-datasource-develop not compactible on Grafana 9. Same plugin was working fine in version 6.

**Comment by christophertjones123** [comment]
so i figured this out at least for my environment. It's probably worth you looking at as well

- extract to /var/lib/grafana/plugins
- Modify /etc/grafana/grafana.ini to allow unsigned plugins
- allow_loading_unsigned_plugins = solarwinds-swis-datasource (make sure to uncomment the line by removing the ";" at the beginning of the line
- restart Grafana service, and you should see it as an available data source.

I've confirmed it works in version 9.1.6

**Comment by odhub** [comment]
![image](https://user-images.githubusercontent.com/7829305/198171772-704b7ea4-e1c3-4e64-923f-4054bb963bc7.png)
Hi,
I follow step define by @christophertjones123 but get error above when try to creare datasources. Anyone has a clue how to solved it ?

**Comment by christophertjones123** [comment]
@odhub take a look at the log. That looks a lot like what I was getting before I modified the Grafana.ini, you could also check to make sure that the Grafana user has rights to the extracted files. Mine didn’t need it but other colleagues that I know have said they’ve had to chown and chgrp to grafana before it would start working. Something else that was super apparent to me that took a little trial and error was also what to download. I basically downloaded the whole develop branch and extracted that to the plugins location.

**Comment by odhub** [comment]
Thank you @christophertjones123 , look like grafana can't all files under /grafana-swis-datasources/ even try to get logo also not found.  I will try downloadwhole develop branch and extracted to the plugins location.
![image](https://user-images.githubusercontent.com/7829305/198177302-32f6fee9-f5a9-4974-801a-6e54b6b64006.png)

**Comment by odhub** [comment]
Hi @christophertjones123 , may i know where you put your plugins ?, seems like in the latest version of grafana on centos/redhat defaults location is   _/usr/share/grafana/public/app/plugins/datasource_ , is it correct to put plugin there ?.
Thank you

**Comment by christophertjones123** [comment]
@odhub the location I put the plug-in is my first bullet point (/var/lib/grafana/plugins). I found out cause I installed a plug-in from the plug-in catalog and then did a search for that plug-in name within my OS, and that’s the location I found them. You could probably do the same thing in case yours is different. I will say I initially thought what you did and then found that directory.

**Comment by etichy** [comment]
Hi, tested with grafana 10.0.0 and it works fine. I updated readme, so enable unsigned plugin is mentioned there.
