### ISSUE TITLE
Show Interface utilization

### ISSUE THREAD

**Issue by junaid360** [etichy/grafana-swis-datasource#2]
Hi, 
How can we pull interface information? need help to create a dashboard to display interface utilization.

**Comment by Atem18** [comment]
@junaid360 You have to create the query.

Try looking in the tables Orion.NPM.InterfaceTraffic and Orion.NPM.Interfaces

**Comment by etichy** [comment]
What exactly do you wanna see? Can you be more specific?

**Comment by junaid360** [comment]
Works in the browser. thank you but when I put in the server I get;

Invalid SWIS uri at character 18: Incomplete uri. Parser did not finish in End state, but instead was left in Scheme state Parameter name: uri

**Comment by junaid360** [comment]
this is how I put on data source filed.

https://localhost:17778/SolarWinds/InformationService/v3/Json/Query?query=SELECT Description FROM System.NullEntity
