### ISSUE TITLE
Alerting support 

### ISSUE THREAD

**Issue by pierre-prevoteau** [etichy/grafana-swis-datasource#20]
Hi 

I'm trying to trigger Grafana's alerts (v8.4.2) from a SWIS datasource but i'm getting a "The datasource does not support alerting queries" error.
![image](https://user-images.githubusercontent.com/97762384/226886443-b4f95a63-2253-4da7-869a-d6aaab240329.png)

I tried to add a` "alerting": true` in the plugin.json but it didn't worked. 

Any idea ? 

Thanks !

**Comment by etichy** [comment]
Hmm that's something new. I'll have to look at it. Thanks

**Comment by pierre-prevoteau** [comment]
We will soon upgrade our Grafana instance to v9.5 : i'll keep you updated if a see any improvement

**Comment by pierre-prevoteau** [comment]
I've found the issue : plugin was indeed missing a `"alerting": true` but not in `/src/plugin.json`, it need to be added in `/dist/plugin.json`.

And voila ! 
![image](https://user-images.githubusercontent.com/97762384/236153494-050f7062-0e61-427a-a75e-0ab5f90c47f0.png)
![image](https://user-images.githubusercontent.com/97762384/236153535-48d234a1-1be7-4c83-80c5-f5c9ac381293.png)

It's working on Grafana v9.5.1 but only with the legacy alerting (which is fine as the new alerting is a pain)

**Comment by etichy** [comment]
Thanks for resolving this one. Change uploaded
