### ISSUE TITLE
EntityNotFoundException

### ISSUE THREAD

**Issue by Netw0rkN1nja** [etichy/grafana-swis-datasource#4]
Hello @etichy ,

Solarwinds recently updated their table names and it looks like the Grafana SWIS Datasource can't find the new names in the SemanticChecker.

`"SolarWinds.Data.Query.EntityNotFoundException: Source entity [SolarwindsOrion.dbo.InterfaceTraffic] not found in catalog at SolarWinds.Data.Query.Processor.SemanticChecker.HandleSourceEntityExpression(SourceExpression sourceExpression) at SolarWinds.Data.Query.Processor.SemanticChecker.Visit(SourceExpression sourceExpression) at SolarWinds.Data.Query.Swql.ParseTreeDuplicatorNoState.Visit(FromClause from) at SolarWinds.Data.Query.Processor.SemanticChecker.Visit(SelectStatement statement) at SolarWinds.Data.Query.Processor.SemanticChecker.Process(SelectStatement statement, PreProcessorState state, String replaceStatementTagWith) at SolarWinds.Data.Query.Processor.SemanticChecker.Process(SelectStatement statement, PreProcessorState state) at SolarWinds.Data.Query.Processor.PreProcessor.Process(SelectStatement selectStatement, PreProcessorState& preProcessorState) at SolarWinds.Data.Query.Engine.QueryProcessor.CompileQueryExecutionPlan(String query, IQueryExecutionContext context) at SolarWinds.InformationService.Core.QueryPlanCache.GetQueryPlan(String query, String username, Boolean federationEnabled, Func`1 buildQueryPlan) at SolarWinds.InformationService.Core.InformationService.GetQueryExecutionPlan(String query, IIdentity currentIdentity, Boolean federationEnabled, IQueryExecutionContext queryExecutionContext) at SolarWinds.InformationService.Core.InformationService.RunQuery(String query, IDictionary`2 parameters, IDataSerializer serializer, IMessageFormatterStrategy messageFormatterStrategy)"`

**Comment by Netw0rkN1nja** [comment]
Looks like this may be an issue with Solarwinds itself as I get the same error message by running the query via Postman.

**Comment by etichy** [comment]
Does it happen for all queries? Can you give me your testing query? thanks

**Comment by Netw0rkN1nja** [comment]
https://solarwinds.company.com:17778/SolarWinds/InformationService/v3/Json/Query?query=

SELECT Interfaces.Caption, DateTime, Interfaces.InPercentUtil AS Download

FROM SolarwindsOrion.dbo.InterfaceTraffic

LEFT JOIN SolarwindsOrion.dbo.Nodes ON (Nodes.NodeID = InterfaceTraffic.NodeID)

LEFT JOIN SolarwindsOrion.dbo.Interfaces ON (Interfaces.InterfaceID = InterfaceTraffic.InterfaceID)

WHERE Interfaces.Circuit_Type = 'ISP' AND Interfaces.Caption like '%ISP2%' AND Nodes.City = '$Site' AND (DATETIME >= DATEADD(day,-29,GETDATE()))

**Comment by Netw0rkN1nja** [comment]
I have a ticket open with Solarwinds but no response yet.  If I hear anything I will let you know.

**Comment by etichy** [comment]
Hi, this is not SWQL query, but it is more SQL query as I can see.  

This is correct SWQL query
```
SELECT Interfaces.Caption, DateTime, Interfaces.InPercentUtil AS Download
FROM Orion.NPM.InterfaceTraffic as InterfaceTraffic
LEFT JOIN Orion.Nodes as Nodes ON (Nodes.NodeID = InterfaceTraffic.NodeID)
LEFT JOIN Orion.NPM.Interfaces as Interfaces ON (Interfaces.InterfaceID = InterfaceTraffic.InterfaceID)
WHERE Interfaces.Circuit_Type = 'ISP' AND 
Interfaces.Caption like '%ISP2%' 
AND Nodes.City = '$Site' 
AND (DATETIME >= ADDDAY(-29,GETUTCDATE()))
```

Also not sure what this query should provide. It will retrieve a lot of data. All interface historical data for last 29 days.

**Comment by etichy** [comment]
It's not issue, closing.
