### ISSUE TITLE
Nested Variables not being interpolated

### ISSUE THREAD

**Issue by mdollemore** [etichy/grafana-swis-datasource#5]
Trying to use a nested variable.
I have defined a NodeId variable;
SELECT Caption as __text, NodeID as __value FROM Orion.Nodes
this works as expected.

However when I try to define an InterfaceID variable as below;-
SELECT Caption as __text, InterfaceID as __value FROM Orion.NPM.Interfaces where NodeID = ($NodeId)

$NodeId is not getting interpolated and just being passed as '($NodeId)' in the query rather than the value of $NodeId.

**Comment by etichy** [comment]
Hmmm let me try that.

**Comment by etichy** [comment]
Hi, thanks for reporting and sorry for slow response. Issue is fixed by [commit](https://github.com/etichy/grafana-swis-datasource/commit/cd13ccc5105b9c9194f776077953a33d492f3c42)
