### ISSUE TITLE
Hover tooltip not refreshing properly

### ISSUE THREAD

**Issue by svestenik** [etichy/grafana-swis-datasource#7]
Hello,

I do not know if this is Grafana or data source related, but when hoover tooltip is set in all series mode, values do not get refreshed properly while moving it over time series graph.

When I set tooltip in single mode, everything works as it should.

**Comment by INGY23** [comment]
Hi,

We are having the same issue and after digging into it, it looks like it’s a issue with grafana. They have reverted some of the code that should be causing it but this was only 9 hours ago. https://github.com/grafana/grafana/pull/26876

Thanks

**Comment by svestenik** [comment]
I am not sure that it is resolved for Solarwinds plugin. On same dashboard I have panels from various sources, Influxdb, Solarwinds, Prometheus. When hoover tooltip is in all series mode, both Prometheus and Influxdb panels update values on tooltip when i move it over the graphs, but swiss-datasource panel just stays stuck on one datapoint.

**Comment by etichy** [comment]
Hmmm ok, I'll look at it, thanks for submitting

**Comment by etichy** [comment]
Is it still actual? It works for me 
![image](https://user-images.githubusercontent.com/17002066/164002920-ace90812-1742-4229-88f9-f5c7d01b751e.png)
