### ISSUE TITLE
Alerting queries for Solarwinds datasource

### ISSUE THREAD

**Issue by svestenik** [etichy/grafana-swis-datasource#9]
Hello,

would it be possible to add Alerting queries for this datasource ?

You did a very fine job on this plugin and it is performing flawlessly so far. It would be very helpful to also include alerts if possible.

**Comment by etichy** [comment]
What would you like to see? Active alerts and alerts history?

**Comment by svestenik** [comment]
Also alerts based on thresholds, I.E. warnings for bandwidth over/under utilization.

**Comment by etichy** [comment]
You can reach any data which are exposed by SWIS, in case you need something specific data maybe I can help to compose that swql query or you can definitely ask for help on [thwack](https://thwack.solarwinds.com)
